before:
  hooks:
    - go mod tidy
builds:
  - id: "aserto-idp-seed-build"
    main: ./cmd/aserto-idp-seed
    binary: aserto-idp-seed
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s 
      - -w 
      - -X github.com/aserto-dev/aserto-idp-seed/pkg/version.ver={{.Version}} 
      - -X github.com/aserto-dev/aserto-idp-seed/pkg/version.commit={{.ShortCommit}} 
      - -X github.com/aserto-dev/aserto-idp-seed/pkg/version.date={{.Date}} 
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md
    name_template: "aserto-idp-seed_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: aserto-dev
    name: aserto-idp-seed

  draft: true
  prerelease: false
  name_template: "{{.Tag}}"

brews:
  -
    name: aserto-idp-seed

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    url_template: "http://github.aserto-dev/aserto-idp-seed/releases/{{ .Tag }}/{{ .ArtifactName }}"

    download_strategy: GitDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://aserto.com/"

    description: "Aserto IDP seed tool"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/aserto-idp-seed version"

    install: |
      bin.install "aserto-idp-seed"
